
void parseparse(); // Defined in file generated by maphoon
void lexme(); // Defined in file generated by flex

int main(){
    // If bothe these link successfully, it means we managed to
    // generate code both with flex and with maphoon!
    parseparse();
    lexme();
}
